#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 21, 2021 10:54:23 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import MTS_matrix_V2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    MTS_matrix_V2_support.set_Tk_var()
    top = Toplevel1 (root)
    MTS_matrix_V2_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    MTS_matrix_V2_support.set_Tk_var()
    top = Toplevel1 (w)
    MTS_matrix_V2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        Font_Display_Type = "Comic Sans MS", 25, "bold"

        top.geometry("931x528+227+101")
        top.minsize(120, 1)
        top.maxsize(1284, 1005)
        top.resizable(1,  1)
        top.title("Remote MTS Matrix Control V1.22")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.CellName1 = tk.Entry(top)
        self.CellName1.place(relx=0.021, rely=0.066, height=20, relwidth=0.09)
        self.CellName1.configure(background="#c0c0c0")
        self.CellName1.configure(disabledforeground="#a3a3a3")
        self.CellName1.configure(font="TkFixedFont")
        self.CellName1.configure(foreground="#000000")
        self.CellName1.configure(highlightbackground="#d9d9d9")
        self.CellName1.configure(highlightcolor="black")
        self.CellName1.configure(insertbackground="black")
        self.CellName1.configure(selectbackground="blue")
        self.CellName1.configure(selectforeground="white")

        self.CellName2 = tk.Entry(top)
        self.CellName2.place(relx=0.097, rely=0.127, height=20, relwidth=0.09)
        self.CellName2.configure(background="#c0c0c0")
        self.CellName2.configure(disabledforeground="#a3a3a3")
        self.CellName2.configure(font="TkFixedFont")
        self.CellName2.configure(foreground="#000000")
        self.CellName2.configure(highlightbackground="#d9d9d9")
        self.CellName2.configure(highlightcolor="black")
        self.CellName2.configure(insertbackground="black")
        self.CellName2.configure(selectbackground="blue")
        self.CellName2.configure(selectforeground="white")

        self.CellName3 = tk.Entry(top)
        self.CellName3.place(relx=0.172, rely=0.063, height=20, relwidth=0.09)
        self.CellName3.configure(background="#c0c0c0")
        self.CellName3.configure(disabledforeground="#a3a3a3")
        self.CellName3.configure(font="TkFixedFont")
        self.CellName3.configure(foreground="#000000")
        self.CellName3.configure(highlightbackground="#d9d9d9")
        self.CellName3.configure(highlightcolor="black")
        self.CellName3.configure(insertbackground="black")
        self.CellName3.configure(selectbackground="blue")
        self.CellName3.configure(selectforeground="white")

        self.CellName4 = tk.Entry(top)
        self.CellName4.place(relx=0.247, rely=0.127, height=20, relwidth=0.09)
        self.CellName4.configure(background="#c0c0c0")
        self.CellName4.configure(disabledforeground="#a3a3a3")
        self.CellName4.configure(font="TkFixedFont")
        self.CellName4.configure(foreground="#000000")
        self.CellName4.configure(highlightbackground="#d9d9d9")
        self.CellName4.configure(highlightcolor="black")
        self.CellName4.configure(insertbackground="black")
        self.CellName4.configure(selectbackground="blue")
        self.CellName4.configure(selectforeground="white")

        self.CellName5 = tk.Entry(top)
        self.CellName5.place(relx=0.322, rely=0.066, height=20, relwidth=0.09)
        self.CellName5.configure(background="#c0c0c0")
        self.CellName5.configure(disabledforeground="#a3a3a3")
        self.CellName5.configure(font="TkFixedFont")
        self.CellName5.configure(foreground="#000000")
        self.CellName5.configure(highlightbackground="#d9d9d9")
        self.CellName5.configure(highlightcolor="black")
        self.CellName5.configure(insertbackground="black")
        self.CellName5.configure(selectbackground="blue")
        self.CellName5.configure(selectforeground="white")

        self.CellName6 = tk.Entry(top)
        self.CellName6.place(relx=0.397, rely=0.127, height=20, relwidth=0.09)
        self.CellName6.configure(background="#c0c0c0")
        self.CellName6.configure(disabledforeground="#a3a3a3")
        self.CellName6.configure(font="TkFixedFont")
        self.CellName6.configure(foreground="#000000")
        self.CellName6.configure(highlightbackground="#d9d9d9")
        self.CellName6.configure(highlightcolor="black")
        self.CellName6.configure(insertbackground="black")
        self.CellName6.configure(selectbackground="blue")
        self.CellName6.configure(selectforeground="white")

        self.CellName7 = tk.Entry(top)
        self.CellName7.place(relx=0.473, rely=0.063, height=20, relwidth=0.09)
        self.CellName7.configure(background="#c0c0c0")
        self.CellName7.configure(disabledforeground="#a3a3a3")
        self.CellName7.configure(font="TkFixedFont")
        self.CellName7.configure(foreground="#000000")
        self.CellName7.configure(highlightbackground="#d9d9d9")
        self.CellName7.configure(highlightcolor="black")
        self.CellName7.configure(insertbackground="black")
        self.CellName7.configure(selectbackground="blue")
        self.CellName7.configure(selectforeground="white")

        self.CellName8 = tk.Entry(top)
        self.CellName8.place(relx=0.548, rely=0.133, height=20, relwidth=0.09)
        self.CellName8.configure(background="#c0c0c0")
        self.CellName8.configure(disabledforeground="#a3a3a3")
        self.CellName8.configure(font="TkFixedFont")
        self.CellName8.configure(foreground="#000000")
        self.CellName8.configure(highlightbackground="#d9d9d9")
        self.CellName8.configure(highlightcolor="black")
        self.CellName8.configure(insertbackground="black")
        self.CellName8.configure(selectbackground="blue")
        self.CellName8.configure(selectforeground="white")

        self.CellName9 = tk.Entry(top)
        self.CellName9.place(relx=0.623, rely=0.066, height=20, relwidth=0.09)
        self.CellName9.configure(background="#c0c0c0")
        self.CellName9.configure(disabledforeground="#a3a3a3")
        self.CellName9.configure(font="TkFixedFont")
        self.CellName9.configure(foreground="#000000")
        self.CellName9.configure(highlightbackground="#d9d9d9")
        self.CellName9.configure(highlightcolor="black")
        self.CellName9.configure(insertbackground="black")
        self.CellName9.configure(selectbackground="blue")
        self.CellName9.configure(selectforeground="white")

        self.CellName10 = tk.Entry(top)
        self.CellName10.place(relx=0.698, rely=0.127, height=20, relwidth=0.09)
        self.CellName10.configure(background="#c0c0c0")
        self.CellName10.configure(disabledforeground="#a3a3a3")
        self.CellName10.configure(font="TkFixedFont")
        self.CellName10.configure(foreground="#000000")
        self.CellName10.configure(highlightbackground="#d9d9d9")
        self.CellName10.configure(highlightcolor="black")
        self.CellName10.configure(insertbackground="black")
        self.CellName10.configure(selectbackground="blue")
        self.CellName10.configure(selectforeground="white")

        self.CellName11 = tk.Entry(top)
        self.CellName11.place(relx=0.773, rely=0.066, height=20, relwidth=0.09)
        self.CellName11.configure(background="#c0c0c0")
        self.CellName11.configure(disabledforeground="#a3a3a3")
        self.CellName11.configure(font="TkFixedFont")
        self.CellName11.configure(foreground="#000000")
        self.CellName11.configure(highlightbackground="#d9d9d9")
        self.CellName11.configure(highlightcolor="black")
        self.CellName11.configure(insertbackground="black")
        self.CellName11.configure(selectbackground="blue")
        self.CellName11.configure(selectforeground="white")

        self.CellName12 = tk.Entry(top)
        self.CellName12.place(relx=0.849, rely=0.133, height=20, relwidth=0.09)
        self.CellName12.configure(background="#c0c0c0")
        self.CellName12.configure(disabledforeground="#a3a3a3")
        self.CellName12.configure(font="TkFixedFont")
        self.CellName12.configure(foreground="#000000")
        self.CellName12.configure(highlightbackground="#d9d9d9")
        self.CellName12.configure(highlightcolor="black")
        self.CellName12.configure(insertbackground="black")
        self.CellName12.configure(selectbackground="blue")
        self.CellName12.configure(selectforeground="white")

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.064, rely=0.112,  relheight=0.178)
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.14, rely=0.178,  relheight=0.112)
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.215, rely=0.112,  relheight=0.178)
        self.TSeparator3.configure(orient="vertical")

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.29, rely=0.178,  relheight=0.112)
        self.TSeparator4.configure(orient="vertical")

        self.TSeparator5 = ttk.Separator(top)
        self.TSeparator5.place(relx=0.365, rely=0.112,  relheight=0.178)
        self.TSeparator5.configure(orient="vertical")

        self.TSeparator6 = ttk.Separator(top)
        self.TSeparator6.place(relx=0.44, rely=0.178,  relheight=0.112)
        self.TSeparator6.configure(orient="vertical")

        self.TSeparator7 = ttk.Separator(top)
        self.TSeparator7.place(relx=0.516, rely=0.112,  relheight=0.178)
        self.TSeparator7.configure(orient="vertical")

        self.TSeparator8 = ttk.Separator(top)
        self.TSeparator8.place(relx=0.591, rely=0.178,  relheight=0.112)
        self.TSeparator8.configure(orient="vertical")

        self.TSeparator9 = ttk.Separator(top)
        self.TSeparator9.place(relx=0.666, rely=0.112,  relheight=0.178)
        self.TSeparator9.configure(orient="vertical")

        self.TSeparator10 = ttk.Separator(top)
        self.TSeparator10.place(relx=0.741, rely=0.178,  relheight=0.112)
        self.TSeparator10.configure(orient="vertical")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(top,
                activebackground="#ececec",
                activeborderwidth=1,
                activeforeground="#000000",
                background="#d9d9d9",
                borderwidth=1,
                disabledforeground="#a3a3a3",
                foreground="#000000",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                label="File")
        self.sub_menu.add_command(command=MTS_matrix_V2_support.Load_File,
                label="Load_labels_from_file")
        self.sub_menu.add_command(command=MTS_matrix_V2_support.Save_File,
                label="Save_labels_to_file")
        self.sub_menu1 = tk.Menu(top,
                activebackground="#ececec",
                activeborderwidth=1,
                activeforeground="#000000",
                background="#d9d9d9",
                borderwidth=1,
                disabledforeground="#a3a3a3",
                foreground="#000000",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                label="About")
        self.sub_menu1.add_command(command=MTS_matrix_V2_support.About,
                label="About")

        self.TSeparator11 = ttk.Separator(top)
        self.TSeparator11.place(relx=0.816, rely=0.112,  relheight=0.178)
        self.TSeparator11.configure(orient="vertical")

        self.TSeparator12 = ttk.Separator(top)
        self.TSeparator12.place(relx=0.892, rely=0.178,  relheight=0.112)
        self.TSeparator12.configure(orient="vertical")

        self.Display1 = tk.Entry(top)
        self.Display1.place(relx=0.043, rely=0.29, height=40, relwidth=0.047)
        self.Display1.configure(background="#000000")
        self.Display1.configure(disabledforeground="#a3a3a3")
        self.Display1.configure(font = Font_Display_Type)
        self.Display1.configure(foreground="#00ff00")
        self.Display1.configure(highlightbackground="#d9d9d9")
        self.Display1.configure(highlightcolor="black")
        self.Display1.configure(insertbackground="black")
        self.Display1.configure(selectbackground="blue")
        self.Display1.configure(selectforeground="white")
        self.Display1.insert(0,"95")

        self.Display2 = tk.Entry(top)
        self.Display2.place(relx=0.118, rely=0.286, height=40, relwidth=0.047)
        self.Display2.configure(background="#000000")
        self.Display2.configure(disabledforeground="#a3a3a3")
        self.Display2.configure(font = Font_Display_Type)
        self.Display2.configure(foreground="#00ff00")
        self.Display2.configure(highlightbackground="#d9d9d9")
        self.Display2.configure(highlightcolor="black")
        self.Display2.configure(insertbackground="black")
        self.Display2.configure(selectbackground="blue")
        self.Display2.configure(selectforeground="white")
        self.Display2.insert(0,"95")

        self.Display3 = tk.Entry(top)
        self.Display3.place(relx=0.193, rely=0.286, height=40, relwidth=0.047)
        self.Display3.configure(background="#000000")
        self.Display3.configure(disabledforeground="#a3a3a3")
        self.Display3.configure(font = Font_Display_Type)
        self.Display3.configure(foreground="#00ff00")
        self.Display3.configure(highlightbackground="#d9d9d9")
        self.Display3.configure(highlightcolor="black")
        self.Display3.configure(insertbackground="black")
        self.Display3.configure(selectbackground="blue")
        self.Display3.configure(selectforeground="white")
        self.Display3.insert(0,"95")

        self.Display4 = tk.Entry(top)
        self.Display4.place(relx=0.269, rely=0.286, height=40, relwidth=0.047)
        self.Display4.configure(background="#000000")
        self.Display4.configure(disabledforeground="#a3a3a3")
        self.Display4.configure(font = Font_Display_Type)
        self.Display4.configure(foreground="#00ff00")
        self.Display4.configure(highlightbackground="#d9d9d9")
        self.Display4.configure(highlightcolor="black")
        self.Display4.configure(insertbackground="black")
        self.Display4.configure(selectbackground="blue")
        self.Display4.configure(selectforeground="white")
        self.Display4.insert(0,"95")

        self.Display5 = tk.Entry(top)
        self.Display5.place(relx=0.344, rely=0.286, height=40, relwidth=0.047)
        self.Display5.configure(background="#000000")
        self.Display5.configure(disabledforeground="#a3a3a3")
        self.Display5.configure(font = Font_Display_Type)
        self.Display5.configure(foreground="#00ff00")
        self.Display5.configure(highlightbackground="#d9d9d9")
        self.Display5.configure(highlightcolor="black")
        self.Display5.configure(insertbackground="black")
        self.Display5.configure(selectbackground="blue")
        self.Display5.configure(selectforeground="white")
        self.Display5.insert(0,"95")

        self.Display6 = tk.Entry(top)
        self.Display6.place(relx=0.419, rely=0.286, height=40, relwidth=0.047)
        self.Display6.configure(background="#000000")
        self.Display6.configure(disabledforeground="#a3a3a3")
        self.Display6.configure(font = Font_Display_Type)
        self.Display6.configure(foreground="#00ff00")
        self.Display6.configure(highlightbackground="#d9d9d9")
        self.Display6.configure(highlightcolor="black")
        self.Display6.configure(insertbackground="black")
        self.Display6.configure(selectbackground="blue")
        self.Display6.configure(selectforeground="white")
        self.Display6.insert(0,"95")

        self.Display7 = tk.Entry(top)
        self.Display7.place(relx=0.494, rely=0.286, height=40, relwidth=0.047)
        self.Display7.configure(background="#000000")
        self.Display7.configure(disabledforeground="#a3a3a3")
        self.Display7.configure(font = Font_Display_Type)
        self.Display7.configure(foreground="#00ff00")
        self.Display7.configure(highlightbackground="#d9d9d9")
        self.Display7.configure(highlightcolor="black")
        self.Display7.configure(insertbackground="black")
        self.Display7.configure(selectbackground="blue")
        self.Display7.configure(selectforeground="white")
        self.Display7.insert(0,"95")

        self.Display8 = tk.Entry(top)
        self.Display8.place(relx=0.569, rely=0.286, height=40, relwidth=0.047)
        self.Display8.configure(background="#000000")
        self.Display8.configure(disabledforeground="#a3a3a3")
        self.Display8.configure(font = Font_Display_Type)
        self.Display8.configure(foreground="#00ff00")
        self.Display8.configure(highlightbackground="#d9d9d9")
        self.Display8.configure(highlightcolor="black")
        self.Display8.configure(insertbackground="black")
        self.Display8.configure(selectbackground="blue")
        self.Display8.configure(selectforeground="white")
        self.Display8.insert(0,"95")

        self.Display9 = tk.Entry(top)
        self.Display9.place(relx=0.644, rely=0.29, height=40, relwidth=0.047)
        self.Display9.configure(background="#000000")
        self.Display9.configure(disabledforeground="#a3a3a3")
        self.Display9.configure(font = Font_Display_Type)
        self.Display9.configure(foreground="#00ff00")
        self.Display9.configure(highlightbackground="#d9d9d9")
        self.Display9.configure(highlightcolor="black")
        self.Display9.configure(insertbackground="black")
        self.Display9.configure(selectbackground="blue")
        self.Display9.configure(selectforeground="white")
        self.Display9.insert(0,"95")

        self.Display10 = tk.Entry(top)
        self.Display10.place(relx=0.72, rely=0.29, height=40, relwidth=0.047)
        self.Display10.configure(background="#000000")
        self.Display10.configure(disabledforeground="#a3a3a3")
        self.Display10.configure(font = Font_Display_Type)
        self.Display10.configure(foreground="#00ff00")
        self.Display10.configure(highlightbackground="#d9d9d9")
        self.Display10.configure(highlightcolor="black")
        self.Display10.configure(insertbackground="black")
        self.Display10.configure(selectbackground="blue")
        self.Display10.configure(selectforeground="white")
        self.Display10.insert(0,"95")

        self.Display11 = tk.Entry(top)
        self.Display11.place(relx=0.795, rely=0.286, height=40, relwidth=0.047)
        self.Display11.configure(background="#000000")
        self.Display11.configure(disabledforeground="#a3a3a3")
        self.Display11.configure(font = Font_Display_Type)
        self.Display11.configure(foreground="#00ff00")
        self.Display11.configure(highlightbackground="#d9d9d9")
        self.Display11.configure(highlightcolor="black")
        self.Display11.configure(insertbackground="black")
        self.Display11.configure(selectbackground="blue")
        self.Display11.configure(selectforeground="white")
        self.Display11.insert(0,"95")

        self.Display12 = tk.Entry(top)
        self.Display12.place(relx=0.87, rely=0.29, height=40, relwidth=0.047)
        self.Display12.configure(background="#000000")
        self.Display12.configure(disabledforeground="#a3a3a3")
        self.Display12.configure(font = Font_Display_Type)
        self.Display12.configure(foreground="#00ff00")
        self.Display12.configure(highlightbackground="#d9d9d9")
        self.Display12.configure(highlightcolor="black")
        self.Display12.configure(insertbackground="black")
        self.Display12.configure(selectbackground="blue")
        self.Display12.configure(selectforeground="white")
        self.Display12.insert(0,"95")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.021, rely=0.443, relheight=0.216
                , relwidth=0.913)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#000040")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Up1 = tk.Button(self.Frame1)
        self.Up1.place(relx=0.024, rely=0.079, height=44, width=47)
        self.Up1.configure(activebackground="#ececec")
        self.Up1.configure(activeforeground="#000000")
        self.Up1.configure(background="#d9d9d9")
        self.Up1.configure(disabledforeground="#a3a3a3")
        self.Up1.configure(foreground="#000000")
        self.Up1.configure(highlightbackground="#d9d9d9")
        self.Up1.configure(highlightcolor="black")
        self.Up1.configure(pady="0")
        self.Up1.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up1_tooltip = \
        ToolTip(self.Up1, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up1.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up1_Left_Click(e))
        self.Up1.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up1_Right_Click(e))

        self.Up2 = tk.Button(self.Frame1)
        self.Up2.place(relx=0.106, rely=0.079, height=44, width=47)
        self.Up2.configure(activebackground="#ececec")
        self.Up2.configure(activeforeground="#000000")
        self.Up2.configure(background="#d9d9d9")
        self.Up2.configure(disabledforeground="#a3a3a3")
        self.Up2.configure(foreground="#000000")
        self.Up2.configure(highlightbackground="#d9d9d9")
        self.Up2.configure(highlightcolor="black")
        self.Up2.configure(pady="0")
        self.Up2.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up2_tooltip = \
        ToolTip(self.Up2, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up2.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up2_Left_Click(e))
        self.Up2.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up2_Right_Click(e))

        self.Up3 = tk.Button(self.Frame1)
        self.Up3.place(relx=0.188, rely=0.07, height=44, width=47)
        self.Up3.configure(activebackground="#ececec")
        self.Up3.configure(activeforeground="#000000")
        self.Up3.configure(background="#d9d9d9")
        self.Up3.configure(disabledforeground="#a3a3a3")
        self.Up3.configure(foreground="#000000")
        self.Up3.configure(highlightbackground="#d9d9d9")
        self.Up3.configure(highlightcolor="black")
        self.Up3.configure(pady="0")
        self.Up3.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up3_tooltip = \
        ToolTip(self.Up3, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up3.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up3_Left_Click(e))
        self.Up3.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up3_Right_Click(e))

        self.Up4 = tk.Button(self.Frame1)
        self.Up4.place(relx=0.271, rely=0.079, height=44, width=47)
        self.Up4.configure(activebackground="#ececec")
        self.Up4.configure(activeforeground="#000000")
        self.Up4.configure(background="#d9d9d9")
        self.Up4.configure(disabledforeground="#a3a3a3")
        self.Up4.configure(foreground="#000000")
        self.Up4.configure(highlightbackground="#d9d9d9")
        self.Up4.configure(highlightcolor="black")
        self.Up4.configure(pady="0")
        self.Up4.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up4_tooltip = \
        ToolTip(self.Up4, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up4.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up4_Left_Click(e))
        self.Up4.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up4_Right_Click(e))

        self.Up5 = tk.Button(self.Frame1)
        self.Up5.place(relx=0.353, rely=0.07, height=44, width=47)
        self.Up5.configure(activebackground="#ececec")
        self.Up5.configure(activeforeground="#000000")
        self.Up5.configure(background="#d9d9d9")
        self.Up5.configure(disabledforeground="#a3a3a3")
        self.Up5.configure(foreground="#000000")
        self.Up5.configure(highlightbackground="#d9d9d9")
        self.Up5.configure(highlightcolor="black")
        self.Up5.configure(pady="0")
        self.Up5.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up5_tooltip = \
        ToolTip(self.Up5, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up5.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up5_Left_Click(e))
        self.Up5.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up5_Right_Click(e))

        self.Up6 = tk.Button(self.Frame1)
        self.Up6.place(relx=0.435, rely=0.07, height=44, width=47)
        self.Up6.configure(activebackground="#ececec")
        self.Up6.configure(activeforeground="#000000")
        self.Up6.configure(background="#d9d9d9")
        self.Up6.configure(disabledforeground="#a3a3a3")
        self.Up6.configure(foreground="#000000")
        self.Up6.configure(highlightbackground="#d9d9d9")
        self.Up6.configure(highlightcolor="black")
        self.Up6.configure(pady="0")
        self.Up6.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up6_tooltip = \
        ToolTip(self.Up6, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up6.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up6_Left_Click(e))
        self.Up6.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up6_Right_Click(e))

        self.Up7 = tk.Button(self.Frame1)
        self.Up7.place(relx=0.518, rely=0.07, height=44, width=47)
        self.Up7.configure(activebackground="#ececec")
        self.Up7.configure(activeforeground="#000000")
        self.Up7.configure(background="#d9d9d9")
        self.Up7.configure(disabledforeground="#a3a3a3")
        self.Up7.configure(foreground="#000000")
        self.Up7.configure(highlightbackground="#d9d9d9")
        self.Up7.configure(highlightcolor="black")
        self.Up7.configure(pady="0")
        self.Up7.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up7_tooltip = \
        ToolTip(self.Up7, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up7.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up7_Left_Click(e))
        self.Up7.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up7_Right_Click(e))

        self.Up8 = tk.Button(self.Frame1)
        self.Up8.place(relx=0.6, rely=0.079, height=44, width=47)
        self.Up8.configure(activebackground="#ececec")
        self.Up8.configure(activeforeground="#000000")
        self.Up8.configure(background="#d9d9d9")
        self.Up8.configure(disabledforeground="#a3a3a3")
        self.Up8.configure(foreground="#000000")
        self.Up8.configure(highlightbackground="#d9d9d9")
        self.Up8.configure(highlightcolor="black")
        self.Up8.configure(pady="0")
        self.Up8.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up8_tooltip = \
        ToolTip(self.Up8, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up8.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up8_Left_Click(e))
        self.Up8.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up8_Right_Click(e))

        self.Up9 = tk.Button(self.Frame1)
        self.Up9.place(relx=0.682, rely=0.07, height=44, width=47)
        self.Up9.configure(activebackground="#ececec")
        self.Up9.configure(activeforeground="#000000")
        self.Up9.configure(background="#d9d9d9")
        self.Up9.configure(disabledforeground="#a3a3a3")
        self.Up9.configure(foreground="#000000")
        self.Up9.configure(highlightbackground="#d9d9d9")
        self.Up9.configure(highlightcolor="black")
        self.Up9.configure(pady="0")
        self.Up9.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up9_tooltip = \
        ToolTip(self.Up9, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up9.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up9_Left_Click(e))
        self.Up9.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up9_Right_Click(e))

        self.Up10 = tk.Button(self.Frame1)
        self.Up10.place(relx=0.765, rely=0.079, height=44, width=47)
        self.Up10.configure(activebackground="#ececec")
        self.Up10.configure(activeforeground="#000000")
        self.Up10.configure(background="#d9d9d9")
        self.Up10.configure(disabledforeground="#a3a3a3")
        self.Up10.configure(foreground="#000000")
        self.Up10.configure(highlightbackground="#d9d9d9")
        self.Up10.configure(highlightcolor="black")
        self.Up10.configure(pady="0")
        self.Up10.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up10_tooltip = \
        ToolTip(self.Up10, self.tooltip_font, '''We All love Mozo...''')
        self.Up10.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up10_Left_Click(e))
        self.Up10.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up10_Right_Click(e))

        self.Up12 = tk.Button(self.Frame1)
        self.Up12.place(relx=0.929, rely=0.07, height=44, width=47)
        self.Up12.configure(activebackground="#ececec")
        self.Up12.configure(activeforeground="#000000")
        self.Up12.configure(background="#d9d9d9")
        self.Up12.configure(disabledforeground="#a3a3a3")
        self.Up12.configure(foreground="#000000")
        self.Up12.configure(highlightbackground="#d9d9d9")
        self.Up12.configure(highlightcolor="black")
        self.Up12.configure(pady="0")
        self.Up12.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up12_tooltip = \
        ToolTip(self.Up12, self.tooltip_font, '''Mouse left click increase by one, mouse right click set to max 95''')
        self.Up12.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up12_Left_Click(e))
        self.Up12.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up12_Right_Click(e))

        self.Dw1 = tk.Button(self.Frame1)
        self.Dw1.place(relx=0.024, rely=0.588, height=44, width=47)
        self.Dw1.configure(activebackground="#ececec")
        self.Dw1.configure(activeforeground="#000000")
        self.Dw1.configure(background="#d9d9d9")
        self.Dw1.configure(disabledforeground="#a3a3a3")
        self.Dw1.configure(foreground="#000000")
        self.Dw1.configure(highlightbackground="#d9d9d9")
        self.Dw1.configure(highlightcolor="black")
        self.Dw1.configure(pady="0")
        self.Dw1.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw1_tooltip = \
        ToolTip(self.Dw1, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw1.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw1_Left_Click(e))
        self.Dw1.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw1_Right_Click(e))

        self.Dw3 = tk.Button(self.Frame1)
        self.Dw3.place(relx=0.188, rely=0.588, height=44, width=47)
        self.Dw3.configure(activebackground="#ececec")
        self.Dw3.configure(activeforeground="#000000")
        self.Dw3.configure(background="#d9d9d9")
        self.Dw3.configure(disabledforeground="#a3a3a3")
        self.Dw3.configure(foreground="#000000")
        self.Dw3.configure(highlightbackground="#d9d9d9")
        self.Dw3.configure(highlightcolor="black")
        self.Dw3.configure(pady="0")
        self.Dw3.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw3_tooltip = \
        ToolTip(self.Dw3, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw3.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw3_Left_Click(e))
        self.Dw3.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw3_Right_Click(e))

        self.Dw4 = tk.Button(self.Frame1)
        self.Dw4.place(relx=0.271, rely=0.588, height=44, width=47)
        self.Dw4.configure(activebackground="#ececec")
        self.Dw4.configure(activeforeground="#000000")
        self.Dw4.configure(background="#d9d9d9")
        self.Dw4.configure(disabledforeground="#a3a3a3")
        self.Dw4.configure(foreground="#000000")
        self.Dw4.configure(highlightbackground="#d9d9d9")
        self.Dw4.configure(highlightcolor="black")
        self.Dw4.configure(pady="0")
        self.Dw4.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw4_tooltip = \
        ToolTip(self.Dw4, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw4.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw4_Left_Click(e))
        self.Dw4.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw4_Right_Click(e))

        self.Dw5 = tk.Button(self.Frame1)
        self.Dw5.place(relx=0.353, rely=0.588, height=44, width=47)
        self.Dw5.configure(activebackground="#ececec")
        self.Dw5.configure(activeforeground="#000000")
        self.Dw5.configure(background="#d9d9d9")
        self.Dw5.configure(disabledforeground="#a3a3a3")
        self.Dw5.configure(foreground="#000000")
        self.Dw5.configure(highlightbackground="#d9d9d9")
        self.Dw5.configure(highlightcolor="black")
        self.Dw5.configure(pady="0")
        self.Dw5.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw5_tooltip = \
        ToolTip(self.Dw5, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw5.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw5_Left_Click(e))
        self.Dw5.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw5_Right_Click(e))

        self.Dw6 = tk.Button(self.Frame1)
        self.Dw6.place(relx=0.435, rely=0.588, height=44, width=47)
        self.Dw6.configure(activebackground="#ececec")
        self.Dw6.configure(activeforeground="#000000")
        self.Dw6.configure(background="#d9d9d9")
        self.Dw6.configure(disabledforeground="#a3a3a3")
        self.Dw6.configure(foreground="#000000")
        self.Dw6.configure(highlightbackground="#d9d9d9")
        self.Dw6.configure(highlightcolor="black")
        self.Dw6.configure(pady="0")
        self.Dw6.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw6_tooltip = \
        ToolTip(self.Dw6, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw6.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw6_Left_Click(e))
        self.Dw6.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw6_Right_Click(e))

        self.Dw7 = tk.Button(self.Frame1)
        self.Dw7.place(relx=0.518, rely=0.588, height=44, width=47)
        self.Dw7.configure(activebackground="#ececec")
        self.Dw7.configure(activeforeground="#000000")
        self.Dw7.configure(background="#d9d9d9")
        self.Dw7.configure(disabledforeground="#a3a3a3")
        self.Dw7.configure(foreground="#000000")
        self.Dw7.configure(highlightbackground="#d9d9d9")
        self.Dw7.configure(highlightcolor="black")
        self.Dw7.configure(pady="0")
        self.Dw7.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw7_tooltip = \
        ToolTip(self.Dw7, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw7.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw7_Left_Click(e))
        self.Dw7.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw7_Right_Click(e))

        self.Dw8 = tk.Button(self.Frame1)
        self.Dw8.place(relx=0.6, rely=0.588, height=44, width=47)
        self.Dw8.configure(activebackground="#ececec")
        self.Dw8.configure(activeforeground="#000000")
        self.Dw8.configure(background="#d9d9d9")
        self.Dw8.configure(disabledforeground="#a3a3a3")
        self.Dw8.configure(foreground="#000000")
        self.Dw8.configure(highlightbackground="#d9d9d9")
        self.Dw8.configure(highlightcolor="black")
        self.Dw8.configure(pady="0")
        self.Dw8.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw8_tooltip = \
        ToolTip(self.Dw8, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw8.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw8_Left_Click(e))
        self.Dw8.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw8_Right_Clik(e))

        self.Dw9 = tk.Button(self.Frame1)
        self.Dw9.place(relx=0.682, rely=0.588, height=44, width=47)
        self.Dw9.configure(activebackground="#ececec")
        self.Dw9.configure(activeforeground="#000000")
        self.Dw9.configure(background="#d9d9d9")
        self.Dw9.configure(disabledforeground="#a3a3a3")
        self.Dw9.configure(foreground="#000000")
        self.Dw9.configure(highlightbackground="#d9d9d9")
        self.Dw9.configure(highlightcolor="black")
        self.Dw9.configure(pady="0")
        self.Dw9.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw9_tooltip = \
        ToolTip(self.Dw9, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw9.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw9_Left_Click(e))
        self.Dw9.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw9_Rigth_Click(e))

        self.Dw10 = tk.Button(self.Frame1)
        self.Dw10.place(relx=0.765, rely=0.588, height=44, width=47)
        self.Dw10.configure(activebackground="#ececec")
        self.Dw10.configure(activeforeground="#000000")
        self.Dw10.configure(background="#d9d9d9")
        self.Dw10.configure(disabledforeground="#a3a3a3")
        self.Dw10.configure(foreground="#000000")
        self.Dw10.configure(highlightbackground="#d9d9d9")
        self.Dw10.configure(highlightcolor="black")
        self.Dw10.configure(pady="0")
        self.Dw10.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw10_tooltip = \
        ToolTip(self.Dw10, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw10.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw10_Left_Click(e))
        self.Dw10.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw10_Right_Click(e))

        self.Dw11 = tk.Button(self.Frame1)
        self.Dw11.place(relx=0.847, rely=0.588, height=44, width=47)
        self.Dw11.configure(activebackground="#ececec")
        self.Dw11.configure(activeforeground="#000000")
        self.Dw11.configure(background="#d9d9d9")
        self.Dw11.configure(disabledforeground="#a3a3a3")
        self.Dw11.configure(foreground="#000000")
        self.Dw11.configure(highlightbackground="#d9d9d9")
        self.Dw11.configure(highlightcolor="black")
        self.Dw11.configure(pady="0")
        self.Dw11.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw11_tooltip = \
        ToolTip(self.Dw11, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw11.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw11_Left_Click(e))
        self.Dw11.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw11_Right_Click(e))

        self.Dw12 = tk.Button(self.Frame1)
        self.Dw12.place(relx=0.929, rely=0.588, height=44, width=47)
        self.Dw12.configure(activebackground="#ececec")
        self.Dw12.configure(activeforeground="#000000")
        self.Dw12.configure(background="#d9d9d9")
        self.Dw12.configure(disabledforeground="#a3a3a3")
        self.Dw12.configure(foreground="#000000")
        self.Dw12.configure(highlightbackground="#d9d9d9")
        self.Dw12.configure(highlightcolor="black")
        self.Dw12.configure(pady="0")
        self.Dw12.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw12_tooltip = \
        ToolTip(self.Dw12, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw12.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw12_Left_Click(e))
        self.Dw12.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw12_Right_Left(e))

        self.Dw2 = tk.Button(self.Frame1)
        self.Dw2.place(relx=0.106, rely=0.588, height=44, width=47)
        self.Dw2.configure(activebackground="#ececec")
        self.Dw2.configure(activeforeground="#000000")
        self.Dw2.configure(background="#d9d9d9")
        self.Dw2.configure(disabledforeground="#a3a3a3")
        self.Dw2.configure(foreground="#000000")
        self.Dw2.configure(highlightbackground="#d9d9d9")
        self.Dw2.configure(highlightcolor="black")
        self.Dw2.configure(pady="0")
        self.Dw2.configure(text='''Down''')
        self.tooltip_font = "TkDefaultFont"
        self.Dw2_tooltip = \
        ToolTip(self.Dw2, self.tooltip_font, '''Mouse left click decrease by one, mouse right click set to min 0''')
        self.Dw2.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Dw2_Left_Click(e))
        self.Dw2.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Dw2_Right_Click(e))

        self.GR1 = tk.Checkbutton(top)
        self.GR1.place(relx=0.032, rely=0.366, relheight=0.04, relwidth=0.069)
        self.GR1.configure(activebackground="#ececec")
        self.GR1.configure(activeforeground="#000000")
        self.GR1.configure(background="#d9d9d9")
        self.GR1.configure(disabledforeground="#a3a3a3")
        self.GR1.configure(foreground="#000000")
        self.GR1.configure(highlightbackground="#d9d9d9")
        self.GR1.configure(highlightcolor="black")
        self.GR1.configure(justify='left')
        self.GR1.configure(variable=MTS_matrix_V2_support.che1)
        self.tooltip_font = "TkDefaultFont"
        self.GR1_tooltip = \
        ToolTip(self.GR1, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR2 = tk.Checkbutton(top)
        self.GR2.place(relx=0.107, rely=0.366, relheight=0.04, relwidth=0.067)
        self.GR2.configure(activebackground="#ececec")
        self.GR2.configure(activeforeground="#000000")
        self.GR2.configure(background="#d9d9d9")
        self.GR2.configure(disabledforeground="#a3a3a3")
        self.GR2.configure(foreground="#000000")
        self.GR2.configure(highlightbackground="#d9d9d9")
        self.GR2.configure(highlightcolor="black")
        self.GR2.configure(justify='left')
        self.GR2.configure(variable=MTS_matrix_V2_support.che2)
        self.tooltip_font = "TkDefaultFont"
        self.GR2_tooltip = \
        ToolTip(self.GR2, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR3 = tk.Checkbutton(top)
        self.GR3.place(relx=0.183, rely=0.366, relheight=0.04, relwidth=0.067)
        self.GR3.configure(activebackground="#ececec")
        self.GR3.configure(activeforeground="#000000")
        self.GR3.configure(background="#d9d9d9")
        self.GR3.configure(disabledforeground="#a3a3a3")
        self.GR3.configure(foreground="#000000")
        self.GR3.configure(highlightbackground="#d9d9d9")
        self.GR3.configure(highlightcolor="black")
        self.GR3.configure(justify='left')
        self.GR3.configure(variable=MTS_matrix_V2_support.che3)
        self.tooltip_font = "TkDefaultFont"
        self.GR3_tooltip = \
        ToolTip(self.GR3, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR4 = tk.Checkbutton(top)
        self.GR4.place(relx=0.258, rely=0.366, relheight=0.04, relwidth=0.069)
        self.GR4.configure(activebackground="#ececec")
        self.GR4.configure(activeforeground="#000000")
        self.GR4.configure(background="#d9d9d9")
        self.GR4.configure(disabledforeground="#a3a3a3")
        self.GR4.configure(foreground="#000000")
        self.GR4.configure(highlightbackground="#d9d9d9")
        self.GR4.configure(highlightcolor="black")
        self.GR4.configure(justify='left')
        self.GR4.configure(variable=MTS_matrix_V2_support.che4)
        self.tooltip_font = "TkDefaultFont"
        self.GR4_tooltip = \
        ToolTip(self.GR4, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR5 = tk.Checkbutton(top)
        self.GR5.place(relx=0.333, rely=0.366, relheight=0.04, relwidth=0.066)
        self.GR5.configure(activebackground="#ececec")
        self.GR5.configure(activeforeground="#000000")
        self.GR5.configure(background="#d9d9d9")
        self.GR5.configure(disabledforeground="#a3a3a3")
        self.GR5.configure(foreground="#000000")
        self.GR5.configure(highlightbackground="#d9d9d9")
        self.GR5.configure(highlightcolor="black")
        self.GR5.configure(justify='left')
        self.GR5.configure(variable=MTS_matrix_V2_support.che5)
        self.tooltip_font = "TkDefaultFont"
        self.GR5_tooltip = \
        ToolTip(self.GR5, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR6 = tk.Checkbutton(top)
        self.GR6.place(relx=0.408, rely=0.366, relheight=0.04, relwidth=0.069)
        self.GR6.configure(activebackground="#ececec")
        self.GR6.configure(activeforeground="#000000")
        self.GR6.configure(background="#d9d9d9")
        self.GR6.configure(disabledforeground="#a3a3a3")
        self.GR6.configure(foreground="#000000")
        self.GR6.configure(highlightbackground="#d9d9d9")
        self.GR6.configure(highlightcolor="black")
        self.GR6.configure(justify='left')
        self.GR6.configure(variable=MTS_matrix_V2_support.che6)
        self.tooltip_font = "TkDefaultFont"
        self.GR6_tooltip = \
        ToolTip(self.GR6, self.tooltip_font, '''Select/deselect this antenna port for group operationn''')

        self.GR7 = tk.Checkbutton(top)
        self.GR7.place(relx=0.483, rely=0.366, relheight=0.04, relwidth=0.066)
        self.GR7.configure(activebackground="#ececec")
        self.GR7.configure(activeforeground="#000000")
        self.GR7.configure(background="#d9d9d9")
        self.GR7.configure(disabledforeground="#a3a3a3")
        self.GR7.configure(foreground="#000000")
        self.GR7.configure(highlightbackground="#d9d9d9")
        self.GR7.configure(highlightcolor="black")
        self.GR7.configure(justify='left')
        self.GR7.configure(variable=MTS_matrix_V2_support.che7)
        self.tooltip_font = "TkDefaultFont"
        self.GR7_tooltip = \
        ToolTip(self.GR7, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR8 = tk.Checkbutton(top)
        self.GR8.place(relx=0.559, rely=0.366, relheight=0.04, relwidth=0.067)
        self.GR8.configure(activebackground="#ececec")
        self.GR8.configure(activeforeground="#000000")
        self.GR8.configure(background="#d9d9d9")
        self.GR8.configure(disabledforeground="#a3a3a3")
        self.GR8.configure(foreground="#000000")
        self.GR8.configure(highlightbackground="#d9d9d9")
        self.GR8.configure(highlightcolor="black")
        self.GR8.configure(justify='left')
        self.GR8.configure(variable=MTS_matrix_V2_support.che8)
        self.tooltip_font = "TkDefaultFont"
        self.GR8_tooltip = \
        ToolTip(self.GR8, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR9 = tk.Checkbutton(top)
        self.GR9.place(relx=0.634, rely=0.366, relheight=0.04, relwidth=0.067)
        self.GR9.configure(activebackground="#ececec")
        self.GR9.configure(activeforeground="#000000")
        self.GR9.configure(background="#d9d9d9")
        self.GR9.configure(disabledforeground="#a3a3a3")
        self.GR9.configure(foreground="#000000")
        self.GR9.configure(highlightbackground="#d9d9d9")
        self.GR9.configure(highlightcolor="black")
        self.GR9.configure(justify='left')
        self.GR9.configure(variable=MTS_matrix_V2_support.che9)
        self.tooltip_font = "TkDefaultFont"
        self.GR9_tooltip = \
        ToolTip(self.GR9, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR10 = tk.Checkbutton(top)
        self.GR10.place(relx=0.709, rely=0.366, relheight=0.04, relwidth=0.067)
        self.GR10.configure(activebackground="#ececec")
        self.GR10.configure(activeforeground="#000000")
        self.GR10.configure(background="#d9d9d9")
        self.GR10.configure(disabledforeground="#a3a3a3")
        self.GR10.configure(foreground="#000000")
        self.GR10.configure(highlightbackground="#d9d9d9")
        self.GR10.configure(highlightcolor="black")
        self.GR10.configure(justify='left')
        self.GR10.configure(variable=MTS_matrix_V2_support.che10)
        self.tooltip_font = "TkDefaultFont"
        self.GR10_tooltip = \
        ToolTip(self.GR10, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR11 = tk.Checkbutton(top)
        self.GR11.place(relx=0.784, rely=0.366, relheight=0.04, relwidth=0.066)
        self.GR11.configure(activebackground="#ececec")
        self.GR11.configure(activeforeground="#000000")
        self.GR11.configure(background="#d9d9d9")
        self.GR11.configure(disabledforeground="#a3a3a3")
        self.GR11.configure(foreground="#000000")
        self.GR11.configure(highlightbackground="#d9d9d9")
        self.GR11.configure(highlightcolor="black")
        self.GR11.configure(justify='left')
        self.GR11.configure(variable=MTS_matrix_V2_support.che11)
        self.tooltip_font = "TkDefaultFont"
        self.GR11_tooltip = \
        ToolTip(self.GR11, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.GR12 = tk.Checkbutton(top)
        self.GR12.place(relx=0.859, rely=0.366, relheight=0.04, relwidth=0.068)
        self.GR12.configure(activebackground="#ececec")
        self.GR12.configure(activeforeground="#000000")
        self.GR12.configure(background="#d9d9d9")
        self.GR12.configure(disabledforeground="#a3a3a3")
        self.GR12.configure(foreground="#000000")
        self.GR12.configure(highlightbackground="#d9d9d9")
        self.GR12.configure(highlightcolor="black")
        self.GR12.configure(justify='left')
        self.GR12.configure(variable=MTS_matrix_V2_support.che12)
        self.tooltip_font = "TkDefaultFont"
        self.GR12_tooltip = \
        ToolTip(self.GR12, self.tooltip_font, '''Select/deselect this antenna port for group operation''')

        self.Up11 = tk.Button(top)
        self.Up11.place(relx=0.795, rely=0.46, height=44, width=47)
        self.Up11.configure(activebackground="#ececec")
        self.Up11.configure(activeforeground="#000000")
        self.Up11.configure(background="#d9d9d9")
        self.Up11.configure(disabledforeground="#a3a3a3")
        self.Up11.configure(foreground="#000000")
        self.Up11.configure(highlightbackground="#d9d9d9")
        self.Up11.configure(highlightcolor="black")
        self.Up11.configure(pady="0")
        self.Up11.configure(text='''Up''')
        self.tooltip_font = "TkDefaultFont"
        self.Up11_tooltip = \
        ToolTip(self.Up11, self.tooltip_font, '''...but Bela is the very first''')
        self.Up11.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Up11_Left_Click(e))
        self.Up11.bind('<Button-3>',lambda e:MTS_matrix_V2_support.Up11_Right_Click(e))

        self.GroupSW = tk.LabelFrame(top)
        self.GroupSW.place(relx=0.032, rely=0.714, relheight=0.184
                , relwidth=0.106)
        self.GroupSW.configure(relief='groove')
        self.GroupSW.configure(foreground="black")
        self.GroupSW.configure(text='''GroupSW''')
        self.GroupSW.configure(background="#8080ff")
        self.GroupSW.configure(highlightbackground="#d9d9d9")
        self.GroupSW.configure(highlightcolor="black")

        self.GR_Up = tk.Button(self.GroupSW)
        self.GR_Up.place(relx=0.101, rely=0.196, height=34, width=77
                , bordermode='ignore')
        self.GR_Up.configure(activebackground="#ececec")
        self.GR_Up.configure(activeforeground="#000000")
        self.GR_Up.configure(background="#d9d9d9")
        self.GR_Up.configure(disabledforeground="#a3a3a3")
        self.GR_Up.configure(foreground="#000000")
        self.GR_Up.configure(highlightbackground="#d9d9d9")
        self.GR_Up.configure(highlightcolor="black")
        self.GR_Up.configure(pady="0")
        self.GR_Up.configure(text='''UP group''')
        self.tooltip_font = "TkDefaultFont"
        self.GR_Up_tooltip = \
        ToolTip(self.GR_Up, self.tooltip_font, '''Increase Attenuaton for antenna port group -left click by one, right click set to max 95''')
        self.GR_Up.bind('<Button-1>',lambda e:MTS_matrix_V2_support.GR_Up_Left_Click(e))
        self.GR_Up.bind('<Button-3>',lambda e:MTS_matrix_V2_support.GR_Up_Right_Click(e))

        self.GR_Dw = tk.Button(self.GroupSW)
        self.GR_Dw.place(relx=0.101, rely=0.608, height=34, width=77
                , bordermode='ignore')
        self.GR_Dw.configure(activebackground="#ececec")
        self.GR_Dw.configure(activeforeground="#000000")
        self.GR_Dw.configure(background="#d9d9d9")
        self.GR_Dw.configure(disabledforeground="#a3a3a3")
        self.GR_Dw.configure(foreground="#000000")
        self.GR_Dw.configure(highlightbackground="#d9d9d9")
        self.GR_Dw.configure(highlightcolor="black")
        self.GR_Dw.configure(pady="0")
        self.GR_Dw.configure(text='''Down group''')
        self.tooltip_font = "TkDefaultFont"
        self.GR_Dw_tooltip = \
        ToolTip(self.GR_Dw, self.tooltip_font, '''Decrease Attenuaton for antenna port group - left click by one, right click set to min 0''')
        self.GR_Dw.bind('<Button-1>',lambda e:MTS_matrix_V2_support.GR_Dw_Left_Click(e))
        self.GR_Dw.bind('<Button-3>',lambda e:MTS_matrix_V2_support.GR_Dw_Right_click(e))

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.15, rely=0.712, relheight=0.182, relwidth=0.606)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#004080")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.IP_address_in = tk.Entry(self.Frame2)
        self.IP_address_in.place(relx=0.266, rely=0.177, height=20, relwidth=0.215)
        self.IP_address_in.configure(background="white")
        self.IP_address_in.configure(disabledforeground="#a3a3a3")
        self.IP_address_in.configure(font="TkFixedFont")
        self.IP_address_in.configure(foreground="#000000")
        self.IP_address_in.configure(highlightbackground="#d9d9d9")
        self.IP_address_in.configure(highlightcolor="black")
        self.IP_address_in.configure(insertbackground="black")
        self.IP_address_in.configure(selectbackground="blue")
        self.IP_address_in.configure(selectforeground="white")
        self.IP_address_in.insert(0,"192.168.83.50")
        self.tooltip_font = "TkDefaultFont"
        self.IP_address_in_tooltip = \
        ToolTip(self.IP_address_in, self.tooltip_font, '''Enter the IP of the MTS here''')

        self.IP_port_in = tk.Entry(self.Frame2)
        self.IP_port_in.place(relx=0.266, rely=0.604, height=20, relwidth=0.109)
        self.IP_port_in.configure(background="white")
        self.IP_port_in.configure(disabledforeground="#a3a3a3")
        self.IP_port_in.configure(font="TkFixedFont")
        self.IP_port_in.configure(foreground="#000000")
        self.IP_port_in.configure(highlightbackground="#d9d9d9")
        self.IP_port_in.configure(highlightcolor="black")
        self.IP_port_in.configure(insertbackground="black")
        self.IP_port_in.configure(selectbackground="blue")
        self.IP_port_in.configure(selectforeground="white")
        self.IP_port_in.insert(0,"4001")
        self.tooltip_font = "TkDefaultFont"
        self.IP_port_in_tooltip = \
        ToolTip(self.IP_port_in, self.tooltip_font, '''Enter the MTS TCP port number here''')

        self.Check1 = tk.Button(self.Frame2)
        self.Check1.place(relx=0.514, rely=0.344, height=24, width=97)
        self.Check1.configure(activebackground="#ececec")
        self.Check1.configure(activeforeground="#000000")
        self.Check1.configure(background="#d9d9d9")
        self.Check1.configure(disabledforeground="#a3a3a3")
        self.Check1.configure(foreground="#000000")
        self.Check1.configure(highlightbackground="#d9d9d9")
        self.Check1.configure(highlightcolor="black")
        self.Check1.configure(pady="0")
        self.Check1.configure(text='''Check Conn''')
        self.tooltip_font = "TkDefaultFont"
        self.Check1_tooltip = \
        ToolTip(self.Check1, self.tooltip_font, '''Button for connection check''')
        self.Check1.bind('<Button-1>',lambda e:MTS_matrix_V2_support.Check_connection_Click(e))

        self.TSeparator13 = ttk.Separator(self.Frame2)
        self.TSeparator13.place(relx=0.693, rely=0.448,  relwidth=0.048)

        self.Entry1 = tk.Entry(self.Frame2)
        self.Entry1.place(relx=0.762, rely=0.344, height=20, relwidth=0.22)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.106, rely=0.177, height=17, width=74)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''IP address''')

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.106, rely=0.604, height=18, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''IP Port''')

# ======================================================
# Support code for Balloon Help (also called tooltips).
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=0.5, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in milliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

    def update(self, msg):
        """
        Updates the Tooltip with a new message. Added by Rozen
        """
        self.msgVar.set(msg)

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

if __name__ == '__main__':
    vp_start_gui()





