#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Feb 17, 2021 08:38:03 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m56" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 621x360+400+200
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1404 1031
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MTS Matrix Remote"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    entry $top.ent45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent46" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent48" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent49" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent50" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent51" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent53" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent54" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent57" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent58" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent59" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 34 
    vTcl:DefineAlias "$top.ent60" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    button $top.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP1 
    vTcl:DefineAlias "$top.but62" "Up1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but62 <Button-1> {
        lambda e: Up1_Click(e)
    }
    button $top.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW1 
    vTcl:DefineAlias "$top.but63" "Dw1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but63 <Button-1> {
        lambda e: Dw1_Click(e)
    }
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP2 
    vTcl:DefineAlias "$top.but64" "Up2" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but64 <Button-1> {
        lambda e: Up2_click(e)
    }
    button $top.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW2 
    vTcl:DefineAlias "$top.but65" "Dw2" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but65 <Button-1> {
        lambda e: Dw2_Click(e)
    }
    button $top.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP3 
    vTcl:DefineAlias "$top.but66" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but66 <Button-1> {
        lambda e: Up3_Click(e)
    }
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW3 
    vTcl:DefineAlias "$top.but67" "Dw3" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but67 <Button-1> {
        lambda e: Dw3_Click(e)
    }
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP4 
    vTcl:DefineAlias "$top.but68" "Button5" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but68 <Button-1> {
        lambda e: Up4_Click(e)
    }
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW4 
    vTcl:DefineAlias "$top.but69" "Dw4" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but69 <Button-1> {
        lambda e: Dw4_Click(e)
    }
    frame $top.fra70 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -width 475 
    vTcl:DefineAlias "$top.fra70" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra70
    label $site_3_0.lab88 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text IpAddress: 
    vTcl:DefineAlias "$site_3_0.lab88" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent89 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent89" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab90 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Port 
    vTcl:DefineAlias "$site_3_0.lab90" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent91 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 124 
    vTcl:DefineAlias "$site_3_0.ent91" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but93 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Check Conn} 
    vTcl:DefineAlias "$site_3_0.but93" "Check1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but93 <Button-1> {
        lambda e: Check_Conn_Click(e)
    }
    entry $site_3_0.ent95 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 94 
    vTcl:DefineAlias "$site_3_0.ent95" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab88 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent89 \
        -in $site_3_0 -x 0 -relx 0.118 -y 0 -rely 0.133 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.057 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent91 \
        -in $site_3_0 -x 0 -relx 0.118 -y 0 -rely 0.533 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but93 \
        -in $site_3_0 -x 0 -relx 0.353 -y 0 -rely 0.267 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent95 \
        -in $site_3_0 -x 0 -relx 0.521 -y 0 -rely 0.4 -width 94 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    button $top.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP5 
    vTcl:DefineAlias "$top.but71" "Button7" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but71 <Button-1> {
        lambda e: Up5_Click(e)
    }
    button $top.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW5 
    vTcl:DefineAlias "$top.but72" "Dw5" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but72 <Button-1> {
        lambda e: Dw5_Click(e)
    }
    button $top.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP6 
    vTcl:DefineAlias "$top.but73" "Button9" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but73 <Button-1> {
        lambda e: Up6_Click(e)
    }
    button $top.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW6 
    vTcl:DefineAlias "$top.but74" "Dw6" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but74 <Button-1> {
        lambda e: Dw6_Click(e)
    }
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP7 
    vTcl:DefineAlias "$top.but75" "Button11" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but75 <Button-1> {
        lambda e: Up7_Click(e)
    }
    button $top.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW7 
    vTcl:DefineAlias "$top.but76" "Dw7" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but76 <Button-1> {
        lambda e: Dw7_Click(e)
    }
    button $top.but77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP8 
    vTcl:DefineAlias "$top.but77" "Button13" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but77 <Button-1> {
        lambda e: Up8_Click(e)
    }
    button $top.but78 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW8 
    vTcl:DefineAlias "$top.but78" "Dw8" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but78 <Button-1> {
        lambda e: Dw8_Click(e)
    }
    button $top.but79 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP9 
    vTcl:DefineAlias "$top.but79" "Button15" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but79 <Button-1> {
        lambda e: Up9_Click(e)
    }
    button $top.but80 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW9 
    vTcl:DefineAlias "$top.but80" "Dw9" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but80 <Button-1> {
        lambda e: Dw9_Click(e)
    }
    button $top.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP10 
    vTcl:DefineAlias "$top.but81" "Button17" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but81 <Button-1> {
        lambda e: Up10_Click(e)
    }
    button $top.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW10 
    vTcl:DefineAlias "$top.but82" "Dw10" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but82 <Button-1> {
        lambda e: Dw10_Click(e)
    }
    button $top.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP11 
    vTcl:DefineAlias "$top.but83" "Button19" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but83 <Button-1> {
        lambda e: Up11_Click(e)
    }
    button $top.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW11 
    vTcl:DefineAlias "$top.but84" "Dw11" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but84 <Button-1> {
        lambda e: Dw11_Click(e)
    }
    button $top.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text UP12 
    vTcl:DefineAlias "$top.but85" "Button21" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but85 <Button-1> {
        lambda e: Up12_Click(e)
    }
    button $top.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DW12 
    vTcl:DefineAlias "$top.but86" "Dw12" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but86 <Button-1> {
        lambda e: Dw12_Click(e)
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent45 \
        -in $top -x 0 -relx 0.019 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.177 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.258 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.338 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.424 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.499 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.58 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.663 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.744 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.824 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.056 -width 34 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but65 \
        -in $top -x 0 -relx 0.101 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.258 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.258 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra70 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.639 -width 0 -relwidth 0.958 \
        -height 0 -relheight 0.208 -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 0 -relx 0.341 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but72 \
        -in $top -x 0 -relx 0.338 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but73 \
        -in $top -x 0 -relx 0.419 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.419 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.499 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but76 \
        -in $top -x 0 -relx 0.499 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 0 -relx 0.58 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but78 \
        -in $top -x 0 -relx 0.58 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but79 \
        -in $top -x 0 -relx 0.663 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but80 \
        -in $top -x 0 -relx 0.66 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but81 \
        -in $top -x 0 -relx 0.744 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but82 \
        -in $top -x 0 -relx 0.741 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but83 \
        -in $top -x 0 -relx 0.824 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but84 \
        -in $top -x 0 -relx 0.821 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but85 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.167 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but86 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.306 -width 37 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

