#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Feb 21, 2021 10:54:20 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m71" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 931x528+227+101
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 1005
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Remote MTS Matrix Control V1.2"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    entry $top.ent45 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent45" "CellName1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent45
    entry $top.ent46 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 84 
    vTcl:DefineAlias "$top.ent46" "CellName2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent47" "CellName3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent48" "CellName4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent49" "CellName5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 84 
    vTcl:DefineAlias "$top.ent50" "CellName6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent51 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent51" "CellName7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 84 
    vTcl:DefineAlias "$top.ent52" "CellName8" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent54" "CellName9" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 84 
    vTcl:DefineAlias "$top.ent55" "CellName10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent56" "CellName11" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background #c0c0c0 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent57" "CellName12" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe61 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe61" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tSe61
    ttk::separator $top.tSe62 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe62" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe63 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe63" "TSeparator3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe64 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe64" "TSeparator4" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe65 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe65" "TSeparator5" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe66 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe66" "TSeparator6" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe67 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe67" "TSeparator7" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe68 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe68" "TSeparator8" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe69 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe69" "TSeparator9" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe70 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe70" "TSeparator10" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $top.m71 add cascade \
        -menu "$top.m71.men45" -command {{}} -label File 
    set site_3_0 $top.m71
    menu $site_3_0.men45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men45 add command \
        -command {#} -label Load_labels_from_file 
    $site_3_0.men45 add command \
        -command {#} -label Save_labels_to_file 
    $top.m71 add cascade \
        -menu "$top.m71.men46" -command {{}} -label Help 
    set site_3_0 $top.m71
    menu $site_3_0.men46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men46 add command \
        -command {#} -label How_to_use 
    $site_3_0.men46 add command \
        -command {#} -label About 
    ttk::separator $top.tSe72 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe72" "TSeparator11" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe73 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe73" "TSeparator12" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent74 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground #00ff00 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent74" "Display1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent74
    entry $top.ent75 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent75" "Display2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent76 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent76" "Display3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent77 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent77" "Display4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent78 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent78" "Display5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent79 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent79" "Display6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent80 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent80" "Display7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent81 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent81" "Display8" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent82 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent82" "Display9" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent83 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent83" "Display10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent84 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent84" "Display11" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent85 \
        -background #000000 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 44 
    vTcl:DefineAlias "$top.ent85" "Display12" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background #000040 -height 136 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 850 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    button $site_3_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but65" "Up1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but65 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but65 <Button-1> {
        lambda e: Up1_Left_Click(e)
    }
    bind $site_3_0.but65 <Button-3> {
        lambda e: Up1_Right_Click(e)
    }
    button $site_3_0.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but66" "Up2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but66 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase Attenuation}
    }
    bind $site_3_0.but66 <Button-1> {
        lambda e: Up2_Left_Click(e)
    }
    bind $site_3_0.but66 <Button-3> {
        lambda e: Up2_Right_Click(e)
    }
    button $site_3_0.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but67" "Up3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but67 <Button-1> {
        lambda e: Up3_Left_Click(e)
    }
    bind $site_3_0.but67 <Button-3> {
        lambda e: Up3_Right_Click(e)
    }
    button $site_3_0.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but68" "Up4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but68 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but68 <Button-1> {
        lambda e: Up4_Left_Click(e)
    }
    bind $site_3_0.but68 <Button-3> {
        lambda e: Up4_Right_Click(e)
    }
    button $site_3_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but70" "Up5" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but70 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but70 <Button-1> {
        lambda e: Up5_Left_Click(e)
    }
    bind $site_3_0.but70 <Button-3> {
        lambda e: Up5_Right_Click(e)
    }
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but71" "Up6" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but71 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but71 <Button-1> {
        lambda e: Up6_Left_Click(e)
    }
    bind $site_3_0.but71 <Button-3> {
        lambda e: Up6_Right_Click(e)
    }
    button $site_3_0.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but72" "Up7" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but72 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but72 <Button-1> {
        lambda e: Up7_Left_Click(e)
    }
    bind $site_3_0.but72 <Button-3> {
        lambda e: Up7_Right_Click(e)
    }
    button $site_3_0.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but73" "Up8" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but73 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but73 <Button-1> {
        lambda e: Up8_Left_Click(e)
    }
    bind $site_3_0.but73 <Button-3> {
        lambda e: Up8_Right_Click(e)
    }
    button $site_3_0.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but74" "Up9" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but74 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but74 <Button-1> {
        lambda e: Up9_Left_Click(e)
    }
    bind $site_3_0.but74 <Button-3> {
        lambda e: Up9_Right_Click(e)
    }
    button $site_3_0.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but75" "Up10" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but75 <<SetBalloon>> {
        set ::vTcl::balloon::%W {We All love Mozo...}
    }
    bind $site_3_0.but75 <Button-1> {
        lambda e: Up10_Left_Click(e)
    }
    bind $site_3_0.but75 <Button-3> {
        lambda e: Up3_Right_Click(e)
    }
    button $site_3_0.but77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but77" "Up12" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but77 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase attenuation}
    }
    bind $site_3_0.but77 <Button-1> {
        lambda e: Up12_Left_Click(e)
    }
    bind $site_3_0.but77 <Button-3> {
        lambda e: Up12_Right_Click(e)
    }
    button $site_3_0.but79 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but79" "Dw1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but79 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but79 <Button-1> {
        lambda e: Dw1_Left_Click(e)
    }
    bind $site_3_0.but79 <Button-3> {
        lambda e: Dw1_Right_Click(e)
    }
    button $site_3_0.but80 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but80" "Dw3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but80 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but80 <Button-1> {
        lambda e: Dw3_Left_Click(e)
    }
    bind $site_3_0.but80 <Button-3> {
        lambda e: Dw3_Right_Click(e)
    }
    button $site_3_0.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but81" "Dw4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but81 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but81 <Button-1> {
        lambda e: Dw4_Left_Click(e)
    }
    bind $site_3_0.but81 <Button-3> {
        lambda e: Dw4_Right_Click(e)
    }
    button $site_3_0.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but82" "Dw5" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but82 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but82 <Button-1> {
        lambda e: Dw5_Left_Click(e)
    }
    bind $site_3_0.but82 <Button-3> {
        lambda e: Dw5_Right_Click(e)
    }
    button $site_3_0.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but83" "Dw6" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but83 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but83 <Button-1> {
        lambda e: Dw6_Left_Click(e)
    }
    bind $site_3_0.but83 <Button-3> {
        lambda e: Dw6_Right_Click(e)
    }
    button $site_3_0.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but84" "Dw7" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but84 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but84 <Button-1> {
        lambda e: Dw7_Left_Click(e)
    }
    bind $site_3_0.but84 <Button-3> {
        lambda e: Dw7_Right_Click(e)
    }
    button $site_3_0.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but85" "Dw8" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but85 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but85 <Button-1> {
        lambda e: Dw8_Left_Click(e)
    }
    bind $site_3_0.but85 <Button-3> {
        lambda e: Dw8_Right_Clik(e)
    }
    button $site_3_0.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but86" "Dw9" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but86 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but86 <Button-1> {
        lambda e: Dw9_Left_Click(e)
    }
    bind $site_3_0.but86 <Button-3> {
        lambda e: Dw9_Rigth_Click(e)
    }
    button $site_3_0.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but87" "Dw10" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but87 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but87 <Button-1> {
        lambda e: Dw10_Left_Click(e)
    }
    bind $site_3_0.but87 <Button-3> {
        lambda e: Dw10_Right_Click(e)
    }
    button $site_3_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but88" "Dw11" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but88 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but88 <Button-1> {
        lambda e: Dw11_Left_Click(e)
    }
    bind $site_3_0.but88 <Button-3> {
        lambda e: Dw11_Right_Click(e)
    }
    button $site_3_0.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but89" "Dw12" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but89 <Button-1> {
        lambda e: Dw12_Left_Click(e)
    }
    bind $site_3_0.but89 <Button-3> {
        lambda e: Dw12_Right_Left(e)
    }
    button $site_3_0.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but90" "Dw2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but90 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease attenuation}
    }
    bind $site_3_0.but90 <Button-1> {
        lambda e: Dw2_Left_Click(e)
    }
    bind $site_3_0.but90 <Button-3> {
        lambda e: Dw2_Left_Click(e)
    }
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.079 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but66 \
        -in $site_3_0 -x 0 -relx 0.106 -y 0 -rely 0.079 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 0 -relx 0.188 -y 0 -rely 0.074 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but68 \
        -in $site_3_0 -x 0 -relx 0.271 -y 0 -rely 0.081 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 0 -relx 0.353 -y 0 -rely 0.074 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 0 -relx 0.435 -y 0 -rely 0.074 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but72 \
        -in $site_3_0 -x 0 -relx 0.518 -y 0 -rely 0.074 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but73 \
        -in $site_3_0 -x 0 -relx 0.6 -y 0 -rely 0.081 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but74 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.074 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but75 \
        -in $site_3_0 -x 0 -relx 0.765 -y 0 -rely 0.081 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but77 \
        -in $site_3_0 -x 0 -relx 0.929 -y 0 -rely 0.074 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but79 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but80 \
        -in $site_3_0 -x 0 -relx 0.188 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but81 \
        -in $site_3_0 -x 0 -relx 0.271 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but82 \
        -in $site_3_0 -x 0 -relx 0.353 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but83 \
        -in $site_3_0 -x 0 -relx 0.435 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but84 \
        -in $site_3_0 -x 0 -relx 0.518 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but85 \
        -in $site_3_0 -x 0 -relx 0.6 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but86 \
        -in $site_3_0 -x 0 -relx 0.682 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 0 -relx 0.765 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 0 -relx 0.847 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but89 \
        -in $site_3_0 -x 0 -relx 0.929 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but90 \
        -in $site_3_0 -x 0 -relx 0.106 -y 0 -rely 0.588 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    checkbutton $top.che52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che1 
    vTcl:DefineAlias "$top.che52" "GR1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che2 
    vTcl:DefineAlias "$top.che53" "GR2" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che3 
    vTcl:DefineAlias "$top.che54" "GR3" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che4 
    vTcl:DefineAlias "$top.che55" "GR4" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che5 
    vTcl:DefineAlias "$top.che56" "GR5" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che6 
    vTcl:DefineAlias "$top.che57" "GR6" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operationn}
    }
    checkbutton $top.che58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che7 
    vTcl:DefineAlias "$top.che58" "GR7" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che58 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che8 
    vTcl:DefineAlias "$top.che60" "GR8" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che60 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che9 
    vTcl:DefineAlias "$top.che61" "GR9" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che61 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che10 
    vTcl:DefineAlias "$top.che62" "GR10" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che62 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che11 
    vTcl:DefineAlias "$top.che63" "GR11" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che63 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    checkbutton $top.che64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -variable che12 
    vTcl:DefineAlias "$top.che64" "GR12" vTcl:WidgetProc "Toplevel1" 1
    bind $top.che64 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select this antenna port for group operation}
    }
    button $top.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Up 
    vTcl:DefineAlias "$top.but76" "Up11" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but76 <<SetBalloon>> {
        set ::vTcl::balloon::%W {...but Bela is the very first}
    }
    bind $top.but76 <Button-1> {
        lambda e: Up11_Left_Click(e)
    }
    bind $top.but76 <Button-3> {
        lambda e: Up11_Right_Click(e)
    }
    labelframe $top.lab91 \
        -font TkDefaultFont -foreground black -text GroupSW \
        -background #8080ff -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 100 
    vTcl:DefineAlias "$top.lab91" "GroupSW" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab91
    button $site_3_0.but92 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {UP group} 
    vTcl:DefineAlias "$site_3_0.but92" "GR_Up" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but92 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Increase Attenuaton for antenna port group}
    }
    bind $site_3_0.but92 <Button-1> {
        lambda e: GR_Up_Left_Click(e)
    }
    bind $site_3_0.but92 <Button-3> {
        lambda e: GR_Up_Right_Click(e)
    }
    button $site_3_0.but93 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Down group} 
    vTcl:DefineAlias "$site_3_0.but93" "GR_Dw" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Decrease Attenuaton for antenna port group}
    }
    bind $site_3_0.but93 <Button-1> {
        lambda e: GR_Dw_Left_Click(e)
    }
    bind $site_3_0.but93 <Button-3> {
        lambda e: GR_Dw_Right_click(e)
    }
    place $site_3_0.but92 \
        -in $site_3_0 -x 0 -relx 0.101 -y 0 -rely 0.198 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but93 \
        -in $site_3_0 -x 0 -relx 0.101 -y 0 -rely 0.609 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra94 \
        -borderwidth 2 -relief groove -background #004080 -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 564 
    vTcl:DefineAlias "$top.fra94" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra94
    entry $site_3_0.ent95 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent95" "IP_address_in" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.ent95 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter the IP of the MTS here}
    }
    entry $site_3_0.ent96 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_3_0.ent96" "IP_port_in" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.ent96 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter the MTS TCP port number here}
    }
    button $site_3_0.but97 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Check Conn} 
    vTcl:DefineAlias "$site_3_0.but97" "Check1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but97 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Button for connection check}
    }
    bind $site_3_0.but97 <Button-1> {
        lambda e: Check_connection_Click(e)
    }
    ttk::separator $site_3_0.tSe98
    vTcl:DefineAlias "$site_3_0.tSe98" "TSeparator13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent100 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 124 
    vTcl:DefineAlias "$site_3_0.ent100" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab102 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {IP address} 
    vTcl:DefineAlias "$site_3_0.lab102" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab103 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {IP Port} 
    vTcl:DefineAlias "$site_3_0.lab103" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent95 \
        -in $site_3_0 -x 0 -relx 0.266 -y 0 -rely 0.174 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent96 \
        -in $site_3_0 -x 0 -relx 0.266 -y 0 -rely 0.609 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but97 \
        -in $site_3_0 -x 0 -relx 0.514 -y 0 -rely 0.348 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe98 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.443 -width 0 \
        -relwidth 0.048 -anchor nw -bordermode inside 
    place $site_3_0.ent100 \
        -in $site_3_0 -x 0 -relx 0.762 -y 0 -rely 0.348 -width 124 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab102 \
        -in $site_3_0 -x 0 -relx 0.106 -y 0 -rely 0.174 -width 0 \
        -relwidth 0.131 -height 0 -relheight 0.183 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 0 -relx 0.106 -y 0 -rely 0.609 -width 0 \
        -relwidth 0.131 -height 0 -relheight 0.183 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent45 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.067 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.097 -y 0 -rely 0.127 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.172 -y 0 -rely 0.063 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.247 -y 0 -rely 0.127 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.322 -y 0 -rely 0.067 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.397 -y 0 -rely 0.127 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.473 -y 0 -rely 0.063 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.548 -y 0 -rely 0.133 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.623 -y 0 -rely 0.067 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.698 -y 0 -rely 0.127 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.773 -y 0 -rely 0.067 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.849 -y 0 -rely 0.133 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe61 \
        -in $top -x 0 -relx 0.064 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.178 -anchor nw -bordermode inside 
    place $top.tSe62 \
        -in $top -x 0 -relx 0.14 -y 0 -rely 0.178 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.111 -anchor nw -bordermode inside 
    place $top.tSe63 \
        -in $top -x 0 -relx 0.215 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.178 -anchor nw -bordermode inside 
    place $top.tSe64 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.178 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.111 -anchor nw -bordermode inside 
    place $top.tSe65 \
        -in $top -x 0 -relx 0.365 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.178 -anchor nw -bordermode inside 
    place $top.tSe66 \
        -in $top -x 0 -relx 0.44 -y 0 -rely 0.178 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.111 -anchor nw -bordermode inside 
    place $top.tSe67 \
        -in $top -x 0 -relx 0.516 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.178 -anchor nw -bordermode inside 
    place $top.tSe68 \
        -in $top -x 0 -relx 0.591 -y 0 -rely 0.178 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.111 -anchor nw -bordermode inside 
    place $top.tSe69 \
        -in $top -x 0 -relx 0.666 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.178 -anchor nw -bordermode inside 
    place $top.tSe70 \
        -in $top -x 0 -relx 0.741 -y 0 -rely 0.178 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.111 -anchor nw -bordermode inside 
    place $top.tSe72 \
        -in $top -x 0 -relx 0.816 -y 0 -rely 0.111 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.178 -anchor nw -bordermode inside 
    place $top.tSe73 \
        -in $top -x 0 -relx 0.892 -y 0 -rely 0.178 -width 0 -relwidth 0.002 \
        -height 0 -relheight 0.111 -anchor nw -bordermode inside 
    place $top.ent74 \
        -in $top -x 0 -relx 0.043 -y 0 -rely 0.289 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent75 \
        -in $top -x 0 -relx 0.118 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent76 \
        -in $top -x 0 -relx 0.193 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent77 \
        -in $top -x 0 -relx 0.269 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent78 \
        -in $top -x 0 -relx 0.344 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 0 -relx 0.419 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent80 \
        -in $top -x 0 -relx 0.494 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent81 \
        -in $top -x 0 -relx 0.569 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent82 \
        -in $top -x 0 -relx 0.644 -y 0 -rely 0.289 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent83 \
        -in $top -x 0 -relx 0.72 -y 0 -rely 0.289 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent84 \
        -in $top -x 0 -relx 0.795 -y 0 -rely 0.286 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent85 \
        -in $top -x 0 -relx 0.87 -y 0 -rely 0.289 -width 44 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.444 -width 0 -relwidth 0.913 \
        -height 0 -relheight 0.216 -anchor nw -bordermode ignore 
    place $top.che52 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.365 -width 0 -relwidth 0.069 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che53 \
        -in $top -x 0 -relx 0.107 -y 0 -rely 0.365 -width 0 -relwidth 0.067 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che54 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.365 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che55 \
        -in $top -x 0 -relx 0.258 -y 0 -rely 0.365 -width 0 -relwidth 0.069 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che56 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.365 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che57 \
        -in $top -x 0 -relx 0.408 -y 0 -rely 0.365 -width 0 -relwidth 0.069 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che58 \
        -in $top -x 0 -relx 0.483 -y 0 -rely 0.365 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che60 \
        -in $top -x 0 -relx 0.559 -y 0 -rely 0.365 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che61 \
        -in $top -x 0 -relx 0.634 -y 0 -rely 0.365 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che62 \
        -in $top -x 0 -relx 0.709 -y 0 -rely 0.365 -width 0 -relwidth 0.067 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che63 \
        -in $top -x 0 -relx 0.784 -y 0 -rely 0.365 -width 0 -relwidth 0.066 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.che64 \
        -in $top -x 0 -relx 0.859 -y 0 -rely 0.365 -width 0 -relwidth 0.068 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.but76 \
        -in $top -x 0 -relx 0.795 -y 0 -rely 0.46 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab91 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.714 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.183 -anchor nw -bordermode ignore 
    place $top.fra94 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.712 -width 0 -relwidth 0.606 \
        -height 0 -relheight 0.182 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

