#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 21, 2021 10:54:27 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global che1
    che1 = tk.IntVar()
    global che2
    che2 = tk.IntVar()
    global che3
    che3 = tk.IntVar()
    global che4
    che4 = tk.IntVar()
    global che5
    che5 = tk.IntVar()
    global che6
    che6 = tk.IntVar()
    global che7
    che7 = tk.IntVar()
    global che8
    che8 = tk.IntVar()
    global che9
    che9 = tk.IntVar()
    global che10
    che10 = tk.IntVar()
    global che11
    che11 = tk.IntVar()
    global che12
    che12 = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Check_connection_Click(p1):
    print('MTS_matrix_V2_support.Check_connection_Click')
    sys.stdout.flush()

def Dw10_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw10_Left_Click')
    sys.stdout.flush()

def Dw10_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw10_Right_Click')
    sys.stdout.flush()

def Dw11_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw11_Left_Click')
    sys.stdout.flush()

def Dw11_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw11_Right_Click')
    sys.stdout.flush()

def Dw12_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw12_Left_Click')
    sys.stdout.flush()

def Dw12_Right_Left(p1):
    print('MTS_matrix_V2_support.Dw12_Right_Left')
    sys.stdout.flush()

def Dw1_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw1_Left_Click')
    sys.stdout.flush()

def Dw1_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw1_Right_Click')
    sys.stdout.flush()

def Dw2_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw2_Left_Click')
    sys.stdout.flush()

def Dw3_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw3_Left_Click')
    sys.stdout.flush()

def Dw3_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw3_Right_Click')
    sys.stdout.flush()

def Dw4_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw4_Left_Click')
    sys.stdout.flush()

def Dw4_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw4_Right_Click')
    sys.stdout.flush()

def Dw5_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw5_Left_Click')
    sys.stdout.flush()

def Dw5_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw5_Right_Click')
    sys.stdout.flush()

def Dw6_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw6_Left_Click')
    sys.stdout.flush()

def Dw6_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw6_Right_Click')
    sys.stdout.flush()

def Dw7_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw7_Left_Click')
    sys.stdout.flush()

def Dw7_Right_Click(p1):
    print('MTS_matrix_V2_support.Dw7_Right_Click')
    sys.stdout.flush()

def Dw8_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw8_Left_Click')
    sys.stdout.flush()

def Dw8_Right_Clik(p1):
    print('MTS_matrix_V2_support.Dw8_Right_Clik')
    sys.stdout.flush()

def Dw9_Left_Click(p1):
    print('MTS_matrix_V2_support.Dw9_Left_Click')
    sys.stdout.flush()

def Dw9_Rigth_Click(p1):
    print('MTS_matrix_V2_support.Dw9_Rigth_Click')
    sys.stdout.flush()

def GR_Dw_Left_Click(p1):
    print('MTS_matrix_V2_support.GR_Dw_Left_Click')
    sys.stdout.flush()

def GR_Dw_Right_click(p1):
    print('MTS_matrix_V2_support.GR_Dw_Right_click')
    sys.stdout.flush()

def GR_Up_Left_Click(p1):
    print('MTS_matrix_V2_support.GR_Up_Left_Click')
    sys.stdout.flush()

def GR_Up_Right_Click(p1):
    print('MTS_matrix_V2_support.GR_Up_Right_Click')
    sys.stdout.flush()

def Up10_Left_Click(p1):
    print('MTS_matrix_V2_support.Up10_Left_Click')
    sys.stdout.flush()

def Up11_Left_Click(p1):
    print('MTS_matrix_V2_support.Up11_Left_Click')
    sys.stdout.flush()

def Up11_Right_Click(p1):
    print('MTS_matrix_V2_support.Up11_Right_Click')
    sys.stdout.flush()

def Up12_Left_Click(p1):
    print('MTS_matrix_V2_support.Up12_Left_Click')
    sys.stdout.flush()

def Up12_Right_Click(p1):
    print('MTS_matrix_V2_support.Up12_Right_Click')
    sys.stdout.flush()

def Up1_Left_Click(p1):
    print('MTS_matrix_V2_support.Up1_Left_Click')
    sys.stdout.flush()

def Up1_Right_Click(p1):
    print('MTS_matrix_V2_support.Up1_Right_Click')
    sys.stdout.flush()

def Up2_Left_Click(p1):
    print('MTS_matrix_V2_support.Up2_Left_Click')
    sys.stdout.flush()

def Up2_Right_Click(p1):
    print('MTS_matrix_V2_support.Up2_Right_Click')
    sys.stdout.flush()

def Up3_Left_Click(p1):
    print('MTS_matrix_V2_support.Up3_Left_Click')
    sys.stdout.flush()

def Up3_Right_Click(p1):
    print('MTS_matrix_V2_support.Up3_Right_Click')
    sys.stdout.flush()

def Up4_Left_Click(p1):
    print('MTS_matrix_V2_support.Up4_Left_Click')
    sys.stdout.flush()

def Up4_Right_Click(p1):
    print('MTS_matrix_V2_support.Up4_Right_Click')
    sys.stdout.flush()

def Up5_Left_Click(p1):
    print('MTS_matrix_V2_support.Up5_Left_Click')
    sys.stdout.flush()

def Up5_Right_Click(p1):
    print('MTS_matrix_V2_support.Up5_Right_Click')
    sys.stdout.flush()

def Up6_Left_Click(p1):
    print('MTS_matrix_V2_support.Up6_Left_Click')
    sys.stdout.flush()

def Up6_Right_Click(p1):
    print('MTS_matrix_V2_support.Up6_Right_Click')
    sys.stdout.flush()

def Up7_Left_Click(p1):
    print('MTS_matrix_V2_support.Up7_Left_Click')
    sys.stdout.flush()

def Up7_Right_Click(p1):
    print('MTS_matrix_V2_support.Up7_Right_Click')
    sys.stdout.flush()

def Up8_Left_Click(p1):
    print('MTS_matrix_V2_support.Up8_Left_Click')
    sys.stdout.flush()

def Up8_Right_Click(p1):
    print('MTS_matrix_V2_support.Up8_Right_Click')
    sys.stdout.flush()

def Up9_Left_Click(p1):
    print('MTS_matrix_V2_support.Up9_Left_Click')
    sys.stdout.flush()

def Up9_Right_Click(p1):
    print('MTS_matrix_V2_support.Up9_Right_Click')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import MTS_matrix_V2
    MTS_matrix_V2.vp_start_gui()




