#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 13, 2024 04:37:40 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import Pulse1a_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 
phase = -1

class AutoPulse:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("893x128+2134+298")
        top.minsize(120, 1)
        top.maxsize(3844, 1181)
        top.resizable(1,  1)
        top.title("AutoPulse")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.032, rely=0.078, relheight=0.352
                , relwidth=0.726)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Display = tk.Label(self.Frame1)
        self.Display.place(relx=0.023, rely=0.222, height=30, width=618)
        self.Display.configure(activebackground="#d9d9d9")
        self.Display.configure(activeforeground="black")
        self.Display.configure(anchor='w')
        self.Display.configure(background="#d9d9d9")
        self.Display.configure(compound='left')
        self.Display.configure(disabledforeground="#a3a3a3")
        self.Display.configure(font="-family {Segoe UI} -size 9")
        self.Display.configure(foreground="#000000")
        self.Display.configure(highlightbackground="#d9d9d9")
        self.Display.configure(highlightcolor="#000000")
        self.Display.configure(text='''Set ENG keyboard, move the application to the upper right corner, then press Button''')

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.032, rely=0.547, relheight=0.43, relwidth=0.675)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="#000000")

        self.Entry1 = tk.Entry(self.Frame2)
        self.Entry1.place(relx=0.05, rely=0.218, height=30, relwidth=0.62)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Courier New} -size 10")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="#000000")
        self.Entry1.configure(insertbackground="#000000")
        self.Entry1.configure(selectbackground="#d9d9d9")
        self.Entry1.configure(selectforeground="black")

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.873, rely=0.313, height=66, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Pulse1a_support.left_click)
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Button''')

def start_up():
    Pulse1a_support.main()

if __name__ == '__main__':
    Pulse1a_support.main()




