#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Dec 15, 2021 01:49:47 PM CET  platform: Windows NT

import sys

from pywinauto.application import Application
from pywinauto import application

import pywinauto.mouse as mouse
import pywinauto.keyboard as keyboard
import win32gui, win32con, win32api
import time

global counter
counter = 0

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def StartClick(phase):
    print('pulse_support.StartClick')
    global counter
    counter += 1
    print(counter)
    if counter == 1:
        w.Entry1.delete(0, 25)
        w.Entry1.insert(0, str("Conn progress VPN1"))
        try:
            app = Application(backend="uia").connect(title_re="Pulse Secure")
            dlg = app.window(title_re=".*Pulse.*")
            dlg.Button43.click()  # Button 43 comming from the control ident printout
            time.sleep(3)
            for x in range(7):
                keyboard.send_keys('t')
            mouse.click(coords=(1053, 752))
            time.sleep(3)
            keyboard.send_keys('ethtoja{TAB}Speter38{ENTER}')
            w.Entry1.delete(0, 25)
            w.Entry1.configure(background="green")
            w.Entry1.insert(0, str("Type OTP"))
        except:
            w.Entry1.delete(0, 25)
            w.Entry1.configure(background="red")
            w.Entry1.insert(0, str("ERROR:Pulse running?"))
            counter -= 1

    if counter == 2:
        otp = w.Entry1.get()
        print(otp)
        mouse.click(coords=(962, 866))
        keyboard.send_keys(otp)
        keyboard.send_keys('{TAB}{ENTER}')
        w.Entry1.delete(0, 35)
        w.Entry1.insert(0, str("Click when logged in VPN1"))

    if counter == 3:
        try:
            app = Application(backend="uia").connect(title_re="Pulse Secure")
            dlg = app.window(title_re=".*Pulse.*")
            dlg.Button39.click()
            w.Entry1.delete(0, 35)
            w.Entry1.insert(0, str("Click when Magyar Telekom login ready"))
        except:
            w.Entry1.delete(0, 25)
            w.Entry1.configure(background="red")
            w.Entry1.insert(0, str("Try Again!"))
            counter -= 1


    if counter == 4:
        mouse.click(coords=(831, 707))
        time.sleep(2)
        keyboard.send_keys('ethtoja{TAB}Er1css0n51!/{ENTER}')
        w.Entry1.delete(0, 35)
        w.Entry1.insert(0, str("END"))

def StartClick2(phase):
    print('pulse_support.StartClick')
    global counter
    counter -= 1
    print(counter)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import pulse

    pulse.vp_start_gui()
