#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Mar 13, 2024 05:31:57 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 893x128+2134+298
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1181
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "AutoPulse"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "AutoPulse" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 45 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 435 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "AutoPulse" 1
    set site_3_0 $top.fra47
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Please set ENG keyboard  and mode the application to the upper right corner" 
    vTcl:DefineAlias "$site_3_0.lab49" "Display" vTcl:WidgetProc "AutoPulse" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.954 -height 0 -relheight 0.667 -anchor nw \
        -bordermode ignore 
    frame "$top.fra48" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 55 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 405 
    vTcl:DefineAlias "$top.fra48" "Frame2" vTcl:WidgetProc "AutoPulse" 1
    set site_3_0 $top.fra48
    entry "$site_3_0.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 374 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry1" vTcl:WidgetProc "AutoPulse" 1
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.049 -y 0 -rely 0.222 -width 374 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "left_click" -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Button" 
    vTcl:DefineAlias "$top.but51" "Button1" vTcl:WidgetProc "AutoPulse" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.078 -width 0 -relwidth 0.725 \
        -height 0 -relheight 0.352 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.547 -width 0 -relwidth 0.675 \
        -height 0 -relheight 0.43 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.873 -y 0 -rely 0.313 -width 87 -relwidth 0 \
        -height 66 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

