#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 13, 2024 04:37:45 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import pyautogui
import time

import Pulse1a

phase = -1
password = "<LAN_PSW>"
password2 = "<CAS PSW>"

#Button coords below
x_coord = [1846,1217,1047,1003,1831]
y_coord = [262,871,963,918,161]

_debug = True # False to eliminate debug printing from callback functions.


def enter_characers(text_to_write):
 text_to_write_array = []
 text_to_write_array = [char for char in text_to_write]
 for char in text_to_write_array:  
  pyautogui.press(char)

def click_on_coord(step):
 x1 = x_coord[step]
 y1 = y_coord[step]
 pyautogui.click(button="left",x=x1,y=y1)

def main(*args):
    '''Main entry point for the application.'''
    global root
    
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Pulse1a.AutoPulse(_top1)

    root.mainloop()

def left_click(*args):
 global phase #Needs to set global in order to access to it
 phase +=1
 if phase == 0:
   click_on_coord(0)
   time.sleep(3)
   click_on_coord(1)
   pyautogui.press('t')
   time.sleep(1)
   for _ in range(5):
       pyautogui.press('down')
   time.sleep(1)
   click_on_coord(2)
   time.sleep(1)
   enter_characers(password)
   time.sleep(1)
   pyautogui.press('enter')
   _w1.Display.configure(text='''Please input your OTP auth psw and press the Button when the Ivanti asks for it''')
  
 if phase == 1:
   otp = _w1.Entry1.get()
   click_on_coord(3)
   enter_characers(otp)
   pyautogui.press('enter')
   _w1.Display.configure(text='''Please wait until the first VPN connection ESTABLIHES, when finished press Button''')
   
 if phase == 2:
   click_on_coord(4)
   time.sleep(5)   
   enter_characers(password2)
   pyautogui.press('enter')
   _w1.Display.configure(text='''Now you should connected to the CAS, next button press closes this appilacation''') 
 
 if phase == 3:
    global top_level
    root.destroy()

  
  
if __name__ == '__main__':
    Pulse1a.start_up()




