#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 17, 2021 04:27:57 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import simple_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    simple_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    simple_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+2597+257")
        top.minsize(120, 1)
        top.maxsize(3844, 1181)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.117, rely=0.133, height=20, relwidth=0.14)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")
        self.Entry1.insert(0,"0")

        self.Up = tk.Button(top)
        self.Up.place(relx=0.333, rely=0.133, height=24, width=47)
        self.Up.configure(activebackground="#ececec")
        self.Up.configure(activeforeground="#000000")
        self.Up.configure(background="#d9d9d9")
        self.Up.configure(disabledforeground="#a3a3a3")
        self.Up.configure(foreground="#000000")
        self.Up.configure(highlightbackground="#d9d9d9")
        self.Up.configure(highlightcolor="black")
        self.Up.configure(pady="0")
        self.Up.configure(text='''UP''')
        self.Up.bind('<Button-1>',lambda e:simple_support.UP_att(e))

        self.DOWN = tk.Button(top)
        self.DOWN.place(relx=0.333, rely=0.222, height=24, width=47)
        self.DOWN.configure(activebackground="#ececec")
        self.DOWN.configure(activeforeground="#000000")
        self.DOWN.configure(background="#d9d9d9")
        self.DOWN.configure(disabledforeground="#a3a3a3")
        self.DOWN.configure(foreground="#000000")
        self.DOWN.configure(highlightbackground="#d9d9d9")
        self.DOWN.configure(highlightcolor="black")
        self.DOWN.configure(pady="0")
        self.DOWN.configure(text='''Down''')
        self.DOWN.bind('<Button-1>',lambda e:simple_support.Down_att(e))

if __name__ == '__main__':
    vp_start_gui()





