#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Feb 17, 2021 04:28:08 PM CET  platform: Windows NT

import sys
import socket
import struct
import time
import binascii

TCP_IP = '192.168.83.50'
TCP_PORT = 4001
BUFFER_SIZE = 1024

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Down_att(p1):
    current_att = eval(w.Entry1.get())
    current_att = current_att - 1
    print('simple_support.Down_att')
    sys.stdout.flush()
    w.Entry1.delete(0,2)
    w.Entry1.insert(0,str(current_att))
    val = 'A5P' + str(current_att)
    message1 = val.encode('utf-8')
    m1 = message1.hex()
    m2 = '02' + m1 + '03'
    print(m1)
    print(m2)
    MESSAGE = binascii.unhexlify(m2)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((TCP_IP, TCP_PORT))
    s.send(MESSAGE)
    s.close()


def UP_att(p1):
    current_att = eval(w.Entry1.get())
    current_att = current_att + 1
    print('simple_support.UP_att')
    sys.stdout.flush()
    w.Entry1.delete(0,2)
    w.Entry1.insert(0,str(current_att))
    val = 'A5P' + str(current_att)
    message1 = val.encode('utf-8')
    m1 = message1.hex()
    m2 = '02' + m1 + '03'
    print(m1)
    print(m2)
    MESSAGE = binascii.unhexlify(m2)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((TCP_IP, TCP_PORT))
    s.send(MESSAGE)
    s.close()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import simple
    simple.vp_start_gui()




